# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haiku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=30)),
                ('line2', models.CharField(max_length=30)),
                ('line3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='haiku',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haiku_nn.Theme'),
        ),
        migrations.AlterUniqueTogether(
            name='haiku',
            unique_together=set([('line1', 'line2', 'line3')]),
        ),
    ]
